name = "ghoststack-proxy"
main = "src/index.js"
compatibility_date = "2024-12-01"
account_id = "e9c5a793d46fd751dcb9e3b65620cb06"

workers_dev = true

[[d1_databases]]
binding = "DB"
database_name = "ghoststack-auth"
database_id = "f0986b1a-b903-407d-8040-25a18a1e7baf"
migrations_dir = "migrations"

[vars]
CORS_ORIGIN = "https://ghoststack.pages.dev"
SLACK_LOG_CHANNEL = "C0B0YHKH4QM"
SLACK_DISPATCH_CHANNEL = "C0B0LGLTLJK"
